In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X = data.iloc[:,3:-1].values
y = data.iloc[:,13].values

In [4]:
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [5]:
#encoding the categorical features

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [9]:
labelencoder_country = LabelEncoder()

In [12]:
X [:,1] = labelencoder_country.fit_transform(X[:,1])

In [13]:
labelencoder_gender = LabelEncoder()
X[:,2] = labelencoder_gender.fit_transform(X[:,2])

In [14]:
#ohe the country

In [15]:
ohe = OneHotEncoder(categorical_features=[1])
X = ohe.fit_transform(X).toarray()

C:\Users\Comrade49\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Comrade49\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [16]:
X = X[:,1:] #removing the dummy variable trap

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state =0)

In [19]:
#feature_scaling

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
sc = StandardScaler()

In [22]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#### making an ann

In [23]:
import keras

Using TensorFlow backend.


In [24]:
from keras.models import Sequential #for initilize the neural network
from keras.layers import Dense #to create layers of arti neural network

In [25]:
#initilising the ANN

In [26]:
classifier = Sequential() #name of the ann is classifier

In [27]:
#adding the input layer and first hidden layer

In [28]:
classifier.add(Dense(units=int((11+1)/2),kernel_initializer = 'uniform', activation='relu', input_shape=(11,)))

In [29]:
#adding the second hidden layer
classifier.add(Dense(units=int((11+1)/2),kernel_initializer = 'uniform', activation='relu'))

In [30]:
#ouput layer
classifier.add(Dense(units= 1,kernel_initializer = 'uniform', activation='sigmoid'))

In [31]:
#compiling the ann  
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy',metrics= ['accuracy'])

# for more than 2 categories then loss categoirical_crossentropy

In [32]:
#fittin the ann to the training set
classifier.fit(X_train,y_train,batch_size = 10 , epochs= 100)

Epoch 1/100
8000/8000 [==============================] - 4s 474us/step - loss: 0.4844 - acc: 0.7956
Epoch 2/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4280 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.4232 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.4197 - acc: 0.8174
Epoch 5/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.4170 - acc: 0.8237
Epoch 6/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4154 - acc: 0.8276
Epoch 7/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.4141 - acc: 0.8291
Epoch 8/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.4125 - acc: 0.8324
Epoch 9/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4112 - acc: 0.8337
Epoch 10/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4104 - acc: 0.8342

8000/8000 [==============================] - 1s 154us/step - loss: 0.4002 - acc: 0.8356
Epoch 82/100
8000/8000 [==============================] - 1s 166us/step - loss: 0.4002 - acc: 0.8345
Epoch 83/100
8000/8000 [==============================] - 1s 166us/step - loss: 0.4002 - acc: 0.8351
Epoch 84/100
8000/8000 [==============================] - 1s 167us/step - loss: 0.4003 - acc: 0.8364
Epoch 85/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.4001 - acc: 0.8341
Epoch 86/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.3999 - acc: 0.8356
Epoch 87/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.4004 - acc: 0.8340
Epoch 88/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4003 - acc: 0.8357
Epoch 89/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.4000 - acc: 0.8362
Epoch 90/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4004 - acc: 0.8337
Epo

In [33]:
#wwe got the accuracy we get the 84% accuracy

In [35]:
y_pred = classifier.predict(X_test)

In [36]:
y_pred

array([[0.15310848],
       [0.31816348],
       [0.18325089],
       ...,
       [0.18104105],
       [0.15568902],
       [0.07212337]], dtype=float32)

In [39]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [40]:
from sklearn.metrics import confusion_matrix

In [41]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[1551,   44],
       [ 277,  128]], dtype=int64)

In [46]:
from sklearn.metrics import accuracy_score


In [47]:
acs = accuracy_score(y_test,y_pred)
acs*100

83.95

In [ ]:
#here we also get the accuracy of ~84%